# Easysearch plugin descriptor file
# This file is used by Maven build to generate plugin-descriptor.properties
# Gradle build generates this file automatically via the esplugin

description=${project.description}
version=${project.version}
name=${plugin.name}
classname=${plugin.classname}
java.version=${maven.compiler.release}
easysearch.version=${easysearch.version}

